name: First Workflow

on: workflow_dispatch

jobs:
    first_job:
        runs-on: uubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v6

        - name: Welcome mesage
          run: echo "This is a Github Job"

        - name: List files
          run: ls

        - name: Read file
          run: cat README.md


        